# print("안녕하세요."+"반갑습니다.")
# print("안녕하세요"*5)
# print("안녕하세요"+10) Error 문자열 + 숫자로 적었기 때문에 에러가 난다.
# print("Hello"[0])
# print("Hello"[1])
# print("Hello"[2])
# print("Hello"[3])
# print("Hello"[4])
# print("Hello"[-1])
# print("Hello"[1:3])
# print("Hello"[2:4])
# print("Hello"[ :3])
# print("Hello"[2: ])
# print("Hello"[100]) 범위를 넘어섰기 때문에 에러가 난다. Error out of index
print(len("Hello"))